### ISSUE TITLE
اشتباه در تبدیل تاریخ ها

### ISSUE THREAD

**Issue by tux-world** [pesiran/SunDate_Picker#1]
سلام دوست عزیز. تو تبدیل تاریخ به نظر میرسه اشتباه زیادی داره رخ میده مثلا شما این مثالی که میزارم تست کنید

        JDF jdf = new JDF();

        jdf.setGregorianDate(2015, 3, 9);
        Log.e("getIranianYear  ", jdf.getIranianDate() + "");

        jdf.setIranianDate(1393, 18, 12);
        Log.e("getGregorianDate  ", jdf.getGregorianDate() + "");

و مورد جالب اینکه چرا همه سالها بهمن ماه ۳۰ روزه هستن؟ مثال همین گیت رو تست کردم که خودتون گذاشتید

**Comment by pesiran** [comment]
سلام.
تبدیل که درست کار کرد. مثال شما مشکل داشت.
jdf.setIranianDate(1393, 18, 12);
رو تغییر بدید به
jdf.setIranianDate(1393, 12, 18);

سال های کبیسه در نظر گرفته نشدن.

**Comment by tux-world** [comment]
سلام خوب دوست عزیز مبنای تاریخ ها همیشه کبیسه رو ابتدا در نظر میگیرن. منم اصلا فکر نمیکردم به هیچ عنوان در نظر نگرفتید. اینطوریک که به درد زیادی نمیخوره. لحاظ کردنش هم فکر نمیکنم انقدرها سخت باشه :)

**Comment by pesiran** [comment]
در اولین فرصت که وقت کنم حتما لحاظ میکنم. اگر هم تا قبل از اون شما انجام دادید اعمال میکنیم.

**Comment by tux-world** [comment]
​راستش کدتون رو خیلی بد نوشتید شرمنده اینو میگم متغیرهایی که تعریف کردید به
سختی قابل شناسایی هستن که چه کاری انجام میدن. خیلی سخت میشه سر در اورد چی
هستن​
